language: ruby
cache: bundler
rvm:
- 2.6.6
before_install: gem install bundler -v 2.1.4
deploy:
  provider: rubygems
  api_key: "9cecfe4c096bd8443684cc6b09274e57"
  on:
    tags: true
    branch: master
    gem: green_garden
